# Generated by Django 4.2.17 on 2026-01-07 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0060_groupkpi'),
        ('poll', '0051_pollpredictionstatement_active_pollproposal_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='PollProposalKPIVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.BigIntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupkpi')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pollproposalkpivote',
            constraint=models.UniqueConstraint(fields=('created_by', 'proposal', 'kpi'), name='unique_pollproposalkpivote'),
        ),
    ]
