# Generated by Django 4.2.17 on 2026-01-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0060_groupkpi'),
        ('poll', '0052_poll_version_pollproposalkpivote_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollProposalKPIVote',
            new_name='PollProposalKPIBet',
        ),
        migrations.RemoveConstraint(
            model_name='pollproposalkpibet',
            name='unique_pollproposalkpivote',
        ),
        migrations.AddConstraint(
            model_name='pollproposalkpibet',
            constraint=models.UniqueConstraint(fields=('created_by', 'proposal', 'kpi'), name='unique_pollproposalkpibet'),
        ),
    ]
