# Generated by Django 4.2.17 on 2026-01-16 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0060_groupkpi'),
        ('poll', '0053_rename_pollproposalkpivote_pollproposalkpibet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollProposalKPIVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupkpi')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pollproposalkpivote',
            constraint=models.UniqueConstraint(fields=('created_by', 'proposal', 'kpi'), name='unique_pollproposalkpivote'),
        ),
    ]
